# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: alpine:latest

pipelines:
  default:
     - step:
          name: Deploy to test
          deployment: staging   # can be test, staging or production.
      # trigger: manual  # Uncomment to make this a manual deployment.
          script:
            - apk add --no-cache git
            - git branch
            - git pull ssh://git@github.com:fernandoassisr/mensageiro.git master
            - git branch -d tmp_deploy || true
            - git checkout -b tmp_deploy
            - git branch -f master tmp_deploy
            - git checkout master
            - git push ssh://git@github.com:fernandoassisr/mensageiro.git master
            - git push ssh://git@github.com:fernandoassisr/mensageiro.git master
          # environment:
          #   name: staging
          #   url: ssh://git@github.com:fernandoassisr/mensageiro.git
          # only:
          # - master        