version: 2
jobs:
  build:
    docker:
      - image: fernandoassissr/mensageiro:teste1
    steps:
      - run: echo 'works'

  test:
    docker:
      - image: fernandoassissr/mensageiro:teste1
    steps:
          name: Test using PHPUnit
          deployment: test   # can be test, staging or production.
          # caches:
          #  - composer
          # trigger: manual  # Uncomment to make this a manual deployment.
          script:
           # - ./install-phpunit.sh  
           - phpunit -c phpunit.xml
  workflows:
    version: 2
    build_and_test:
      jobs:
        - build
        - test