version: 2
jobs:

  build:
    docker:
      - image: fernandoassissr/mensageiro:teste1
    steps:
      - run:
          name: echo localiza
          command: pwd
      - run:
          name: echo listar
          command: ls
      - run:
          name: entrar diretorio
          command: cd mensageiro
      - run:
          name: phpunit Test suite case
          command: phpunit -c phpunit.xml
