version: 2
jobs:

  test:
    docker:
      - image: fernandoassissr/mensageiro:teste1
    steps:
      - run:
          name: phpunit Test suite case
          command: phpunit -c phpunit.xml

  workflows:
    version: 2
    test:
      jobs:
        - test