version: 2
jobs:

  build:
    docker:
      - image: fernandoassissr/mensageiro:teste1
    steps:
    working_directory: ~/mensageiro
      - run:
          name: echo localiza
          command: pwd
      - run:
          name: "Fix CIRCLE_WORKING_DIRECTORY"
          command: echo 'CIRCLE_WORKING_DIRECTORY="${CIRCLE_WORKING_DIRECTORY/#\~/$HOME}"' >> $BASH_ENV
      - run:
          name: "Tree everything"
          command: tree
      - run:
          name: phpunit Test suite case
          command: phpunit