version: 2
jobs:

  build:
    docker:
      - image: fernandoassissr/mensageiro:teste1
    steps:
      - run:
          name: echo localiza
          command: pwd
      - run:
          name: phpunit Test suite case
          command: phpunit -c {{ CIRCLE_WORKING_DIRECTORY }} ./phpunit.xml