version: '2'
services:

  php:
    container_name: php_mensageiro
    image: php:5.6-fpm
    restart: always
    ports:
      - "9000:9000"
    privileged: true
    volumes:
      - /var/www/html:/var/www/html
    tty: true
    env_file:
      - ./.ENV
    networks:
      - myapp

  web:
    container_name: web_mensageiro
    image: nginx:stable
    restart: always
    ports:
      - "80:80"
      - "8088:8088"
    links:
      - php
    privileged: true
    volumes:
      - /var/www/html:/usr/share/nginx/html/
      - ./log/nginx:/var/log/nginx/
    env_file:
      - ./.ENV
    networks:
      - myapp

  mysql:
    container_name: mysql_mensageiro
    image: mysql:5.7
    restart: always
    privileged: true
    ports:
      - "3306:3306"
    expose:
      - 3306
    volumes:
      - "/var/lib/mysql/:/var/lib/mysql/"
    env_file:
      - ./.ENV
    networks:
      - myapp
      - database

networks:
  myapp:
    driver: bridge
  database:
    driver: bridge